### ISSUE TITLE
Patching

### ISSUE THREAD

**Issue by eddieajau** [ghaiklor/generator-sails-rest-api#45]
@ghaiklor I was looking over the code and thinking about patching. What if we did something like, for example, taking the services and breaking them into discrete, published modules like `sails-service-cipher`, `sails-service-mailer`, and so on.

`CipherService.js` would then become, simply:

```js
module.exports = require('sails-service-cipher');
```

That would make it trivial to add new ciphers, mailers, payment gateways, etc and so on in the future without the generator code being affected. It would also make isolating tests much easier.

If you like that idea, we might be able to talk to Sails about auto-registering services like they do for hooks, or, we could create a custom user hook to do just that anyway.

What do you think?

**Comment by ghaiklor** [comment]
@eddieajau I'm already thinking about this too. The problem here, that Sails can't autoregister services, so yes, we need to talk and hope that they are agree with us to implement this.
I already done with many passport strategies as separate modules and want to do this with services. In that case we will have small percent of code that can be affected with generator update and everything else will be updating just as usual module.
I'm agree with you :+1:

**Comment by ghaiklor** [comment]
@eddieajau I have moved all the services to separate npm modules - a8bea2707a874b708b59694353c9992c9646713a

So my next step it's done some stuff in generator and start working with each of this services. You can find them in my repos.
